package com.pixelbloom.payment.requestDto;

import com.pixelbloom.payment.constants.PaymentPurpose;
import lombok.Data;

import java.math.BigDecimal;

@Data
public class CreateOrderRequest {
    private Long customerId;       // visitorId or memberId
    private String orderNumber;    // generated by caller e.g. ORD-20260320-12345
    private BigDecimal amount;
    private String currency;       // INR
    private String paymentMethod;  // UPI, CARD, NETBANKING
    private PaymentPurpose purpose;
    private String callbackUrl;    // where payment-service POSTs the result
}
